import { useEffect, useState } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { Utensils, Zap, ScanLine, Package, MapPin, Search, ArrowLeft, Camera, X, Check, Navigation, Info } from 'lucide-react'
import { useApp, useRequireAuth } from '../lib/context'
import { supabase, uploadPhoto } from '../lib/supabase'
import { distanceKm, distanceText, errorMessage } from '../lib/utils'
import { MobileHeader } from '../components/Shell'
import { Modal, Button, TastyStar, RatingInput, IconButton, PageHeading, Loading } from '../components/ui'
import { Guide } from '../components/Guide'

export function Create(){
  const {restaurants,location,requestLocation,user,notify,loading}=useApp();const requireAuth=useRequireAuth();const [selected,setSelected]=useState(''),[choose,setChoose]=useState(false),[guide,setGuide]=useState(false),[checkin,setCheckin]=useState(false),[rating,setRating]=useState(4),[busy,setBusy]=useState(false),[query,setQuery]=useState('')
  const ordered=[...restaurants].sort((a,b)=>location?distanceKm(location.lat,location.lng,a)-distanceKm(location.lat,location.lng,b):a.name.localeCompare(b.name))
  const place=restaurants.find(r=>r.id===selected)||ordered[0]
  if(loading)return <Loading/>
  return <div className="create-page"><MobileHeader info onInfo={()=>setGuide(true)}/><PageHeading eyebrow="O QUE VAMOS COMPARTILHAR?" title="Toda garfada tem uma história."><IconButton label="Como funciona" onClick={()=>setGuide(true)}><Info/></IconButton></PageHeading><section className="create-surface"><div className="place-question"><span className="place-question-icon"><Utensils/></span><div><span>{location?'E aí, você está no':'Vamos falar de'}</span><h2>{place?.name || 'um lugar especial'}?</h2></div></div>{!location&&<button className="use-location" onClick={()=>void requestLocation()}><Navigation size={16}/>Encontrar onde estou</button>}<p className="or-place">Ou você está no…</p><div className="place-alternatives">{ordered.filter(r=>r.id!==place?.id).slice(0,2).map(r=><button key={r.id} onClick={()=>setSelected(r.id)}><MapPin size={23}/><strong>{r.name}</strong><span>{location?distanceText(distanceKm(location.lat,location.lng,r)):r.category}</span></button>)}</div><button className="other-place" onClick={()=>setChoose(true)}><Search size={16}/>Não, estou em outro lugar!</button><div className="action-grid"><Link to={`/write?restaurant=${place?.id||''}`} className="action-tile green"><span className="tile-icon"><Utensils/></span><span className="tile-eyebrow">POSTAR</span><h3>Avaliar<br/>um prato</h3><span className="tile-detail">O que vale a pena provar?</span></Link><button className="action-tile yellow" onClick={()=>{if(requireAuth())setCheckin(true)}}><span className="tile-icon"><Zap/></span><span className="tile-eyebrow">STATUS</span><h3>Check-in<br/>rápido</h3><span className="tile-detail">Estive aqui. E adorei.</span></button><Link to="/bill" className="action-tile white"><span className="tile-icon"><ScanLine/></span><span className="tile-eyebrow">PAGAMENTO</span><h3>Conta Justa</h3><span className="tile-detail">Cada um paga o seu.</span></Link><Link to={`/write?kind=delivery&restaurant=${place?.id||''}`} className="action-tile pink"><span className="tile-icon"><Package/></span><span className="tile-eyebrow">PEDIDO</span><h3>Delivery</h3><span className="tile-detail">Do restaurante até você.</span></Link></div></section>
    {choose&&<Modal title="Onde você está?" onClose={()=>setChoose(false)}><div className="search-field"><Search size={20}/><input placeholder="Pesquisar restaurante" aria-label="Pesquisar restaurante" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="place-picker">{restaurants.filter(r=>r.name.toLowerCase().includes(query.toLowerCase())).map(r=><button key={r.id} onClick={()=>{setSelected(r.id);setChoose(false)}}><img src={r.image_url} alt=""/><span><strong>{r.name}</strong><small>{r.category}</small></span>{r.id===place?.id?<Check/>:<MapPin size={18}/>}</button>)}</div></Modal>}
    {guide&&<Modal title="Guia Tasty" className="guide-modal" onClose={()=>setGuide(false)}><Guide onDone={()=>setGuide(false)}/></Modal>}
    {checkin&&<Modal title="Marque sua presença" onClose={()=>setCheckin(false)}><div className="checkin-form"><TastyStar/><h2>{place?.name}</h2><p>Uma nota, uma boa lembrança.</p><RatingInput value={rating} onChange={setRating} label="Como foi sua visita?"/><Button loading={busy} onClick={async()=>{if(!place||!user)return;setBusy(true);const {error}=await supabase.from('checkins').insert({user_id:user.id,restaurant_id:place.id,rating});setBusy(false);if(error)notify(errorMessage(error),'error');else{setCheckin(false);notify('Check-in registrado! Mais uma descoberta na sua história.')}}}><Zap size={18}/>Fazer check-in</Button></div></Modal>}
  </div>
}
export function WriteReview(){
  const {user,profile,restaurants,dishes,refresh,notify}=useApp();const requireAuth=useRequireAuth();const [params]=useSearchParams();const navigate=useNavigate();const delivery=params.get('kind')==='delivery'
  const [restaurant,setRestaurant]=useState(params.get('restaurant')||''),[dish,setDish]=useState(params.get('dish')||''),[rating,setRating]=useState(4),[service,setService]=useState(4),[ambience,setAmbience]=useState(4),[content,setContent]=useState(''),[recommend,setRecommend]=useState(true),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(false)
  const choices=dishes.filter(d=>d.restaurant_id===restaurant)
  useEffect(()=>{if(!file){setPreview('');return}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file])
  async function submit(e:React.FormEvent){e.preventDefault();if(!requireAuth())return;if(!profile){setError('Seu perfil está sendo preparado. Tente novamente em instantes.');return}setBusy(true);setError('');try{
    if(!dish||!restaurant)throw new Error('Escolha o restaurante e o prato que você provou.')
    const photo=file?await uploadPhoto(file,user!.id):null
    const {error}=await supabase.from('reviews').insert({user_id:user!.id,restaurant_id:restaurant,dish_id:dish,rating,content:content.trim(),photo_url:photo,kind:delivery?'delivery':'review',recommend,...(delivery?{packaging_rating:service,delivery_rating:ambience}:{service_rating:service,ambience_rating:ambience})})
    if(error)throw error;await refresh();setSuccess(true)
  }catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
  if(success)return <div className="review-success"><div className="success-stars"><TastyStar/><TastyStar/><TastyStar/></div><h1>Boa comida merece<br/>ser compartilhada.</h1><p>Sua avaliação já está no feed. Obrigado por colocar mais sabor na comunidade!</p><Button onClick={()=>navigate('/')}>Ver minha avaliação<Check size={20}/></Button><Link to={`/dish/${dish}`}>Voltar para o prato</Link></div>
  return <div className="write-page"><Link className="back-link" to="/create"><ArrowLeft size={20}/>Voltar</Link><PageHeading eyebrow={delivery?'DA COZINHA ATÉ A SUA CASA':'SUA OPINIÃO VALE CADA GARFADA'} title={delivery?'Como foi o delivery?':'O que você provou?'} text="O prato é a estrela. Conte sua experiência."/><form className="review-form form-stack" onSubmit={submit}><div className="form-row"><label>Restaurante<select required value={restaurant} onChange={e=>{setRestaurant(e.target.value);setDish('')}}><option value="">Escolha o restaurante</option>{restaurants.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Prato<select required value={dish} onChange={e=>setDish(e.target.value)} disabled={!restaurant}><option value="">Escolha o prato</option>{choices.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label></div><div className={`photo-upload ${preview?'has-photo':''}`}>{preview?<><img src={preview} alt="Prévia da sua foto"/><IconButton label="Remover foto" onClick={()=>setFile(null)}><X size={18}/></IconButton></>:<label><Camera size={30}/><strong>Esse prato merece uma foto</strong><span>Toque para adicionar · JPG, PNG ou WebP · Até 8 MB</span><input type="file" aria-label="Adicionar foto do prato" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f){if(f.size>8*1024*1024)notify('Escolha uma foto de até 8 MB.','error');else setFile(f)}}}/></label>}</div><RatingInput label="A estrela da mesa: o prato" value={rating} onChange={setRating}/><div className="secondary-ratings"><RatingInput label={delivery?'Embalagem':'Serviço'} value={service} onChange={setService}/><RatingInput label={delivery?'Entrega':'Ambiente'} value={ambience} onChange={setAmbience}/></div><label>Conta pra gente<textarea required minLength={1} maxLength={3000} value={content} onChange={e=>setContent(e.target.value)} placeholder="O ponto perfeito, o tempero surpreendente, o que você pediria de novo…" rows={4}/><span className="character-count">{content.length}/3000</span></label><label className="recommend-toggle"><span><strong>Eu pediria de novo!</strong><small>Você recomenda esse prato?</small></span><input type="checkbox" checked={recommend} onChange={e=>setRecommend(e.target.checked)}/><span className={`switch ${recommend?'on':''}`}/></label>{error&&<p className="form-error" role="alert">{error}</p>}<Button type="submit" loading={busy}><TastyStar/>Publicar avaliação</Button><p className="form-footnote">Sua avaliação e foto ficam visíveis para a comunidade.</p></form></div>
}
