import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { Heart, MessageCircle, Send, Bookmark, MapPin, MoreHorizontal, Utensils, Flag, Trash2, Check, Plus, ArrowUpRight } from 'lucide-react'
import { useApp, useRequireAuth } from '../lib/context'
import { errorMessage, timeAgo, money } from '../lib/utils'
import { supabase } from '../lib/supabase'
import type { Review, Profile, Comment, Dish, Restaurant } from '../lib/types'
import { Avatar, TastyStar, IconButton, Modal, Button, EmptyState } from './ui'

export function FollowButton({person,compact=false}:{person:Profile;compact?:boolean}){
  const {following,toggleFollow,user,notify}=useApp();const requireAuth=useRequireAuth();const [busy,setBusy]=useState(false)
  if(person.id===user?.id)return null
  const follows=following.includes(person.id)
  return <button className={`follow-button ${follows?'following':''} ${compact?'compact':''}`} disabled={busy} aria-label={`${follows?'Deixar de seguir':'Seguir'} ${person.username}`} onClick={async()=>{if(!requireAuth())return;setBusy(true);try{await toggleFollow(person.id)}catch(e){notify(errorMessage(e),'error')}finally{setBusy(false)}}}>{follows?<Check size={15}/>:compact?<Plus size={16}/>:null}{follows?'Seguindo':'Seguir'}</button>
}
export function ReviewCard({review}:{review:Review}) {
  const {user,bookmarks,toggleBookmark,notify,setReviews,refresh}=useApp();const requireAuth=useRequireAuth()
  const [comments,setComments]=useState(false),[menu,setMenu]=useState(false),[expanded,setExpanded]=useState(false),[busy,setBusy]=useState(false)
  const liked=review.likes.some(l=>l.user_id===user?.id)
  async function like(){if(!requireAuth()||busy)return;setBusy(true);try{
    const {error}=liked?await supabase.from('likes').delete().eq('review_id',review.id).eq('user_id',user!.id):await supabase.from('likes').insert({review_id:review.id,user_id:user!.id})
    if(error)throw error
    setReviews(list=>list.map(r=>r.id===review.id?{...r,likes:liked?r.likes.filter(l=>l.user_id!==user!.id):[...r.likes,{user_id:user!.id}]}:r))
  }catch(e){notify(errorMessage(e),'error')}finally{setBusy(false)}}
  async function share(){try{const url=`${window.location.origin}/review/${review.id}`;if(navigator.share)await navigator.share({title:`${review.dishes.name} no Tasty`,url});else{await navigator.clipboard.writeText(url);notify('Link da avaliação copiado!')}}catch(e){if(!(e instanceof DOMException&&e.name==='AbortError'))notify('Não foi possível compartilhar. Tente novamente.','error')}}
  return <article className="review-card"><div className="review-place"><Link to={`/restaurant/${review.restaurant_id}`}><MapPin size={17}/><strong>{review.restaurants.name}</strong><span>{review.restaurants.category}</span><ChevronMini/></Link><div><time dateTime={review.created_at}>{timeAgo(review.created_at)}</time><IconButton label={`Mais opções da avaliação de ${review.profiles.username}`} onClick={()=>setMenu(true)}><MoreHorizontal size={21}/></IconButton></div></div>
    <div className="review-photo"><Link to={`/dish/${review.dish_id}`} className="review-photo-link" aria-label={`Ver ${review.dishes.name}`}><img src={review.photo_url || review.dishes.image_url} alt={review.dishes.name} loading="lazy"/></Link><Link to={`/people/${review.user_id}`} className="review-author"><Avatar profile={review.profiles} size={38}/><span><strong>{review.profiles.username}</strong>{review.profiles.is_demo&&<small>Perfil de exemplo</small>}</span></Link><TastyStar value={Number(review.rating)} className="review-score"/><Link to={`/dish/${review.dish_id}`} className="photo-dish-label"><span>{review.dishes.category}</span><strong>{review.dishes.name}<ArrowUpRight size={20}/></strong></Link></div>
    <div className="review-body"><p className={expanded?'':'clamp-2'}>{review.content}</p>{review.content.length>100&&<button className="read-more" onClick={()=>setExpanded(!expanded)}>{expanded?'ver menos':'ver mais'}</button>}<div className="review-actions"><button className={liked?'liked':''} aria-label={liked?'Descurtir avaliação':'Curtir avaliação'} aria-pressed={liked} disabled={busy} onClick={like}><Heart fill={liked?'currentColor':'none'}/><span>{review.likes.length||''}</span></button><button aria-label="Ver comentários" onClick={()=>setComments(true)}><MessageCircle/><span>{review.comments.length||''}</span></button><IconButton label="Compartilhar avaliação" onClick={share}><Send/></IconButton><IconButton label={bookmarks.includes(review.dish_id)?'Remover prato dos salvos':'Salvar prato'} className={bookmarks.includes(review.dish_id)?'saved':''} onClick={async()=>{if(!requireAuth())return;try{await toggleBookmark(review.dish_id)}catch(e){notify(errorMessage(e),'error')}}}><Bookmark fill={bookmarks.includes(review.dish_id)?'currentColor':'none'}/></IconButton><span className="review-kind"><Utensils size={20}/><span>{review.kind==='delivery'?'Delivery':'Prato avaliado'}</span></span></div></div>
    {comments&&<CommentsModal review={review} onClose={()=>setComments(false)}/>}
    {menu&&<Modal title="Sobre esta avaliação" onClose={()=>setMenu(false)}><div className="menu-options"><button onClick={()=>{setMenu(false);void share()}}><Send size={20}/>Compartilhar avaliação</button>{user?.id===review.user_id?<button className="danger-text" onClick={async()=>{const {error}=await supabase.from('reviews').delete().eq('id',review.id).eq('user_id',user.id);if(error)notify(errorMessage(error),'error');else{setMenu(false);notify('Avaliação excluída.');void refresh()}}}><Trash2 size={20}/>Excluir minha avaliação</button>:<ReportButton review={review} close={()=>setMenu(false)}/>}</div>{review.profiles.is_demo&&<p className="muted small">Esta publicação faz parte do catálogo de demonstração do Tasty.</p>}</Modal>}
  </article>
}
function ChevronMini(){return <span className="chevron-mini">›</span>}
function ReportButton({review,close}:{review:Review;close:()=>void}){const [reason,setReason]=useState(''),[open,setOpen]=useState(false),[busy,setBusy]=useState(false);const requireAuth=useRequireAuth();const {user,notify}=useApp();return open?<form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);const {error}=await supabase.from('reports').upsert({user_id:user!.id,review_id:review.id,reason},{onConflict:'user_id,review_id'});setBusy(false);if(error)notify(errorMessage(error),'error');else{notify('Denúncia registrada. Obrigado por ajudar a comunidade.');close()}}}><label>O que aconteceu?<textarea value={reason} onChange={e=>setReason(e.target.value)} minLength={3} maxLength={1000} required placeholder="Descreva o problema com esta publicação"/></label><Button loading={busy} type="submit">Enviar denúncia</Button></form>:<button className="danger-text" onClick={()=>{if(requireAuth())setOpen(true)}}><Flag size={20}/>Denunciar publicação</button>}
export function CommentsModal({review,onClose}:{review:Review;onClose:()=>void}){
  const {user,profile,notify,setReviews}=useApp();const requireAuth=useRequireAuth();const [items,setItems]=useState<Comment[]>([]),[text,setText]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true)
  useEffect(()=>{supabase.from('comments').select('*,profiles!comments_user_id_fkey(*)').eq('review_id',review.id).order('created_at').then(({data,error})=>{if(error)notify(errorMessage(error),'error');else setItems(data as unknown as Comment[]);setLoading(false)})},[review.id,notify])
  return <Modal title="Na mesa da conversa" onClose={onClose}><p className="muted">{review.dishes.name} · {review.restaurants.name}</p><div className="comments-list">{loading?<p>Carregando comentários…</p>:items.length===0?<EmptyState title="Puxe uma cadeira" text="Seja a primeira pessoa a comentar esse prato."/>:items.map(c=><div className="comment" key={c.id}><Avatar profile={c.profiles} size={34}/><div><strong>{c.profiles.username}<small>{timeAgo(c.created_at)}</small></strong><p>{c.content}</p></div>{c.user_id===user?.id&&<IconButton label="Excluir comentário" onClick={async()=>{const {error}=await supabase.from('comments').delete().eq('id',c.id);if(error)notify(errorMessage(error),'error');else{setItems(list=>list.filter(x=>x.id!==c.id));setReviews(list=>list.map(r=>r.id===review.id?{...r,comments:r.comments.filter(x=>x.id!==c.id)}:r))}}}><Trash2 size={15}/></IconButton>}</div>)}</div><form className="comment-form" onSubmit={async e=>{e.preventDefault();if(!requireAuth())return;setBusy(true);const {data,error}=await supabase.from('comments').insert({user_id:user!.id,review_id:review.id,content:text.trim()}).select('*,profiles!comments_user_id_fkey(*)').single();setBusy(false);if(error)notify(errorMessage(error),'error');else{setItems(list=>[...list,data as unknown as Comment]);setText('');setReviews(list=>list.map(r=>r.id===review.id?{...r,comments:[...r.comments,{id:data.id}]}:r))}}}><Avatar profile={profile} size={36}/><input aria-label="Seu comentário" placeholder="Deu água na boca?" value={text} onChange={e=>setText(e.target.value)} maxLength={1000} required/><IconButton label="Enviar comentário" type="submit" disabled={busy||!text.trim()}><Send size={21}/></IconButton></form></Modal>
}
export function DishCard({dish,restaurant}:{dish:Dish;restaurant?:Restaurant}){const {bookmarks,toggleBookmark,notify}=useApp();const requireAuth=useRequireAuth();return <article className="dish-card"><div className="dish-card-image"><Link to={`/dish/${dish.id}`}><img src={dish.image_url} alt={dish.name} loading="lazy"/></Link><TastyStar value={dish.review_count?Number(dish.rating):'–'}/><IconButton label={bookmarks.includes(dish.id)?'Remover dos salvos':'Salvar prato'} className={bookmarks.includes(dish.id)?'saved':''} onClick={async()=>{if(!requireAuth())return;try{await toggleBookmark(dish.id)}catch(e){notify(errorMessage(e),'error')}}}><Bookmark size={19} fill={bookmarks.includes(dish.id)?'currentColor':'none'}/></IconButton></div><Link to={`/dish/${dish.id}`} className="dish-card-info"><small>{restaurant?.name || dish.category}</small><h3>{dish.name}</h3><span>{money(dish.price)}<ArrowUpRight size={17}/></span></Link></article>}
